% =========================================================================
% F_RL_EEG_analysis_from_features.m
%
% EEG-FEATURE × BEHAVIOURAL RL ANALYSIS
% Category Switch Braille Go/NoGo Task
%
% Run AFTER:
%   D_Bayesian_RL_models_behaviour_only.m
%
% INPUTS
%   Results/Simulation results/Figures/nassar_results.mat
%       -> results struct from Nassar 2010 fits
%   Results/Simulation results/Figures/sim_data.mat
%       -> behavioural Bayesian simulation outputs
%   Results/EEG analysis/Epoched_data/group_feature_table_combined_v9c.mat
%       -> combined EEG feature table generated by the EEG feature pipeline
%
% OUTPUTS
%   group_feature_table_combined_v9c_RL.mat
%       -> EEG feature table + Nassar latents joined by (subjID, block, trial)
%   RL_EEG_figures/*.pdf and *.png
%       -> EEG/RL control and hypothesis plots
%
% DESIGN PRINCIPLE
%   Keep behavioural model fitting independent of EEG features.  This script
%   is the only place where EEG columns are joined to behavioural RL latents.
% =========================================================================

clear; close all; rng(42);
set(groot,'defaultAxesTickDir','out');
set(groot,'defaultAxesBox','off');

% =========================================================================
%% §1 PATHS AND LOADING
% =========================================================================
remote = 0;
switch remote
    case 1
        base_path = '/Volumes/PHARM_BANERJEE/data/Projects/EEG_projects/Salient_Modality_Switch/Salient mod switch KH';
    case 0
        base_path = '\\humerus\pharm_banerjee\data\Projects\EEG_projects\Salient_Modality_Switch\Salient mod switch KH';
    case 2
        base_path = 'Z:\data\Projects\EEG_projects\Salient_Modality_Switch\Salient mod switch KH';
end

sim_path = fullfile(base_path, 'Results', 'Simulation results', 'Figures');
eeg_path = fullfile(base_path, 'Results', 'EEG analysis', 'Epoched_data');
outpath  = fullfile(sim_path, 'RL_EEG_figures');
if ~exist(outpath,'dir'), mkdir(outpath); end

results_file = fullfile(sim_path, 'nassar_results.mat');
sim_file     = fullfile(sim_path, 'sim_data.mat');
feature_file = fullfile(eeg_path, 'group_feature_table_combined_v9c.mat');
rl_feature_file = fullfile(eeg_path, 'group_feature_table_combined_v9c_RL.mat');

assert(exist(results_file,'file')==2, 'Missing nassar_results.mat. Run D_Bayesian_RL_models_behaviour_only.m first.');
assert(exist(feature_file,'file')==2, 'Missing group_feature_table_combined_v9c.mat. Generate the combined EEG feature table first.');

load(results_file, 'results');
if exist(sim_file,'file')==2
    load(sim_file, 'sim_data', 'model_vars', 'params'); %#ok<NASGU>
else
    warning('sim_data.mat not found. EEG/RL analyses will continue without simulation objects.');
end

tmp = load(feature_file);
if isfield(tmp,'group_table_combined')
    group_T = tmp.group_table_combined;
elseif isfield(tmp,'group_T')
    group_T = tmp.group_T;
else
    error('Feature file must contain group_table_combined or group_T.');
end
clear tmp;

% Standardise key variable names used by the join.
group_T = standardise_key_columns_lc(group_T);

fprintf('\n========================================================\n');
fprintf('F_RL_EEG_analysis_from_features.m\n');
fprintf('Loaded EEG feature table: %d rows × %d columns\n', height(group_T), width(group_T));
fprintf('Loaded Nassar results for %d subjects\n', numel(fieldnames(results)));
fprintf('Output folder: %s\n', outpath);
fprintf('========================================================\n\n');

% =========================================================================
%% §2 JOIN NASSAR LATENTS TO EEG FEATURE TABLE
% =========================================================================
required_keys = {'subjID','block','trial'};
for kk = 1:numel(required_keys)
    assert(ismember(required_keys{kk}, group_T.Properties.VariableNames), ...
        'EEG feature table missing key column: %s', required_keys{kk});
end

group_T = add_nassar_to_group_table_lc(group_T, results);
group_T = add_behavioural_derived_columns_lc(group_T);

save(rl_feature_file, 'group_T', '-v7.3');
fprintf('Saved RL-enriched EEG feature table:\n  %s\n', rl_feature_file);

% =========================================================================
%% §3 DISCOVER EEG FEATURE COLUMNS
% =========================================================================
model_cols = {'PE_nassar','omega','alpha_nassar','certainty','surprise','theta_nassar'};
key_cols = {'subjID','subj_id','subject','block','blocknum','trial','trialnum','revTrial','rel_trial', ...
    'block_type','prev_block_type','transition','stimID','stimType','stim_status','switch_stims', ...
    'correct','confidence','RT','trueFB','goTrial','respWasGo','perceivedCorrect','n_prev_P','n_prev_P_bin'};

eeg_cols = find_eeg_feature_columns_lc(group_T, [model_cols key_cols]);
if isempty(eeg_cols)
    error(['No numeric EEG feature columns were detected. Check group_feature_table_combined_v9c.mat. ' ...
           'Expected names usually include FRN, P300/P3, theta, power, PLV, amp, or latency.']);
end
fprintf('Detected %d candidate EEG feature columns.\n', numel(eeg_cols));
fprintf('First detected features:\n');
disp(eeg_cols(1:min(20,numel(eeg_cols)))');

% Prefer interpretable named features first for plots.
preferred_features = prioritize_eeg_features_lc(eeg_cols);
plot_features = preferred_features(1:min(12,numel(preferred_features)));

% =========================================================================
%% §4 FIGURE F1: MISSINGNESS AND FEATURE INVENTORY
% =========================================================================
fig1 = figure('Position',[50 50 1300 560]);
sgtitle('EEG/RL input QC: feature availability and joined Nassar latents', 'FontSize',12);

ax1 = subplot(1,3,1); hold(ax1,'on');
latent_present = mean(~isnan(group_T{:,model_cols}), 1);
bar(ax1, latent_present, 'FaceAlpha',0.75, 'EdgeColor','none');
set(ax1,'XTick',1:numel(model_cols),'XTickLabel',model_cols,'XTickLabelRotation',45);
ylabel(ax1,'Fraction non-NaN'); ylim(ax1,[0 1]);
title(ax1,'Joined RL latent coverage');

ax2 = subplot(1,3,2); hold(ax2,'on');
miss = nan(numel(plot_features),1);
for ii = 1:numel(plot_features)
    miss(ii) = mean(isnan(group_T.(plot_features{ii})));
end
barh(ax2, miss, 'FaceAlpha',0.75, 'EdgeColor','none');
set(ax2,'YTick',1:numel(plot_features),'YTickLabel',plot_features);
xlabel(ax2,'Fraction missing'); xlim(ax2,[0 1]);
title(ax2,'Top EEG feature missingness');

ax3 = subplot(1,3,3); hold(ax3,'on');
if ismember('block_type', group_T.Properties.VariableNames)
    bt = categorical(string(group_T.block_type));
    cats = categories(bt);
    counts = countcats(bt);
    bar(ax3, counts, 'FaceAlpha',0.75, 'EdgeColor','none');
    set(ax3,'XTick',1:numel(cats),'XTickLabel',cats);
    ylabel(ax3,'Rows'); title(ax3,'Rows by block type');
else
    text(ax3,0.5,0.5,'No block_type column','HorizontalAlignment','center'); axis(ax3,'off');
end

saveas(fig1, fullfile(outpath,'F1_EEG_RL_QC.pdf'));
saveas(fig1, fullfile(outpath,'F1_EEG_RL_QC.png'));

% =========================================================================
%% §5 FIGURE F2: EEG FEATURES CORRELATED WITH RL LATENTS
% =========================================================================
fprintf('\n=== Correlating EEG features with RL latents ===\n');
R = nan(numel(eeg_cols), numel(model_cols));
P = nan(numel(eeg_cols), numel(model_cols));
N = nan(numel(eeg_cols), numel(model_cols));
for fi = 1:numel(eeg_cols)
    y = group_T.(eeg_cols{fi});
    for mi = 1:numel(model_cols)
        x = group_T.(model_cols{mi});
        ok = isfinite(x) & isfinite(y);
        N(fi,mi) = sum(ok);
        if sum(ok) > 10
            [R(fi,mi), P(fi,mi)] = corr(x(ok), y(ok), 'Type','Spearman', 'Rows','complete');
        end
    end
end

fig2 = figure('Position',[50 50 1500 720]);
sgtitle('Spearman correlations: EEG features × behavioural RL latents', 'FontSize',12);

[~,rank_i] = sort(max(abs(R),[],2,'omitnan'), 'descend');
show_i = rank_i(1:min(40,numel(rank_i)));
ax = axes(fig2); %#ok<LAXES>
imagesc(ax, R(show_i,:));
colormap(ax, bluewhitered_lc(256));
cb = colorbar(ax); ylabel(cb,'Spearman \rho');
caxis(ax,[-max(abs(R(:)),[],'omitnan') max(abs(R(:)),[],'omitnan')]);
set(ax,'XTick',1:numel(model_cols),'XTickLabel',model_cols, ...
       'YTick',1:numel(show_i),'YTickLabel',eeg_cols(show_i), ...
       'TickLabelInterpreter','none');
xtickangle(ax,45);
title(ax,'Top EEG features ranked by max |\rho|');

% Mark nominal p<.05 with dots.
for rr = 1:numel(show_i)
    for cc = 1:numel(model_cols)
        if P(show_i(rr),cc) < 0.05
            text(ax, cc, rr, '*', 'HorizontalAlignment','center', 'Color','k', 'FontWeight','bold');
        end
    end
end

saveas(fig2, fullfile(outpath,'F2_EEG_RL_correlation_heatmap.pdf'));
saveas(fig2, fullfile(outpath,'F2_EEG_RL_correlation_heatmap.png'));

% Save correlation table for inspection.
corr_T = table;
for fi = 1:numel(eeg_cols)
    for mi = 1:numel(model_cols)
        newrow = table(string(eeg_cols{fi}), string(model_cols{mi}), R(fi,mi), P(fi,mi), N(fi,mi), ...
            'VariableNames', {'EEG_feature','RL_latent','rho','p','n'});
        corr_T = [corr_T; newrow]; %#ok<AGROW>
    end
end
corr_T = sortrows(corr_T, 'p', 'ascend');
writetable(corr_T, fullfile(outpath,'F2_EEG_RL_correlations.csv'));

% =========================================================================
%% §6 FIGURE F3: BINNED LATENT EFFECTS FOR TOP FEATURES
% =========================================================================
fig3 = figure('Position',[50 50 1500 860]);
sgtitle('Binned EEG responses by behavioural RL latent magnitude', 'FontSize',12);

latent_to_plot = {'omega','surprise','PE_nassar','certainty'};
latent_labels  = {'\omega change-point probability','surprise = \omega|\delta|','prediction error \delta','certainty |\theta-0.5|'};
features_to_plot = plot_features(1:min(4,numel(plot_features)));

for li = 1:numel(latent_to_plot)
    for fi = 1:numel(features_to_plot)
        ax = subplot(numel(features_to_plot), numel(latent_to_plot), (fi-1)*numel(latent_to_plot)+li); hold(ax,'on');
        x = group_T.(latent_to_plot{li});
        y = group_T.(features_to_plot{fi});
        plot_binned_lc(ax, x, y, 5);
        if fi == 1, title(ax, latent_labels{li}, 'Interpreter','tex'); end
        if li == 1, ylabel(ax, features_to_plot{fi}, 'Interpreter','none'); end
        if fi == numel(features_to_plot), xlabel(ax, 'Latent quintile'); end
    end
end

saveas(fig3, fullfile(outpath,'F3_binned_EEG_by_RL_latents.pdf'));
saveas(fig3, fullfile(outpath,'F3_binned_EEG_by_RL_latents.png'));

% =========================================================================
%% §7 FIGURE F4: SWITCHED/MAINTAINED AND REVERSAL EFFECTS
% =========================================================================
fig4 = figure('Position',[50 50 1450 760]);
sgtitle('EEG features by stimulus status and reversal epoch', 'FontSize',12);

features_to_plot = plot_features(1:min(6,numel(plot_features)));
for fi = 1:numel(features_to_plot)
    ax = subplot(2,3,fi); hold(ax,'on');
    y = group_T.(features_to_plot{fi});
    [stim_status, epoch] = get_stim_and_epoch_lc(group_T);
    cats_stim = ["maintained","switched"];
    cats_epoch = ["pre","post"];
    xbase = 1;
    xt = {}; xpos = [];
    for si = 1:numel(cats_stim)
        for ei = 1:numel(cats_epoch)
            m = stim_status == cats_stim(si) & epoch == cats_epoch(ei) & isfinite(y);
            vals = y(m);
            x = xbase;
            if ~isempty(vals)
                bar(ax,x,mean(vals,'omitnan'),0.65,'FaceAlpha',0.65,'EdgeColor','none','HandleVisibility','off');
                errorbar(ax,x,mean(vals,'omitnan'),sem_lc(vals),'k.','LineWidth',1.2,'CapSize',6,'HandleVisibility','off');
                text(ax,x,mean(vals,'omitnan'),sprintf(' n=%d',numel(vals)),'FontSize',6,'Color',[0.4 0.4 0.4]);
            end
            xt{end+1} = sprintf('%s\n%s', cats_stim(si), cats_epoch(ei)); %#ok<AGROW>
            xpos(end+1) = x; %#ok<AGROW>
            xbase = xbase + 1;
        end
        xbase = xbase + 0.5;
    end
    set(ax,'XTick',xpos,'XTickLabel',xt,'FontSize',8);
    title(ax,features_to_plot{fi},'Interpreter','none','FontSize',9);
    ylabel(ax,'EEG feature value');
end

saveas(fig4, fullfile(outpath,'F4_EEG_switch_epoch_effects.pdf'));
saveas(fig4, fullfile(outpath,'F4_EEG_switch_epoch_effects.png'));

% =========================================================================
%% §8 OPTIONAL LME MODELS
% =========================================================================
fprintf('\n=== Optional LME models: EEG_feature ~ omega + surprise + PE + certainty + covariates + (1|subjID) ===\n');
model_summaries = table;
if exist('fitlme','file') == 2
    for fi = 1:numel(plot_features)
        feat = plot_features{fi};
        Tm = group_T(:, intersect(group_T.Properties.VariableNames, ...
            {'subjID','block_type','stim_status','rel_trial','PE_nassar','omega','alpha_nassar','certainty','surprise',feat}, 'stable'));
        Tm.y = group_T.(feat);
        Tm.subjID = categorical(string(group_T.subjID));
        if ismember('block_type', group_T.Properties.VariableNames)
            Tm.block_type = categorical(string(group_T.block_type));
        end
        if ismember('stim_status', group_T.Properties.VariableNames)
            Tm.stim_status = categorical(string(group_T.stim_status));
        end
        keep = isfinite(Tm.y) & isfinite(Tm.omega) & isfinite(Tm.surprise) & isfinite(Tm.PE_nassar) & isfinite(Tm.certainty);
        Tm = Tm(keep,:);
        if height(Tm) < 50 || numel(categories(Tm.subjID)) < 4
            continue;
        end
        try
            if ismember('block_type', Tm.Properties.VariableNames) && ismember('stim_status', Tm.Properties.VariableNames)
                formula = 'y ~ omega + surprise + PE_nassar + certainty + block_type + stim_status + (1|subjID)';
            elseif ismember('block_type', Tm.Properties.VariableNames)
                formula = 'y ~ omega + surprise + PE_nassar + certainty + block_type + (1|subjID)';
            else
                formula = 'y ~ omega + surprise + PE_nassar + certainty + (1|subjID)';
            end
            lme = fitlme(Tm, formula);
            coefT = lme.Coefficients;
            writetable(coefT, fullfile(outpath, sprintf('LME_%s_coefficients.csv', matlab.lang.makeValidName(feat))));
            for ci = 1:height(coefT)
                row = table(string(feat), string(coefT.Name{ci}), coefT.Estimate(ci), coefT.SE(ci), coefT.tStat(ci), coefT.pValue(ci), height(Tm), ...
                    'VariableNames', {'EEG_feature','term','estimate','SE','t','p','n'});
                model_summaries = [model_summaries; row]; %#ok<AGROW>
            end
            fprintf('  %s: LME fitted, n=%d\n', feat, height(Tm));
        catch ME
            fprintf('  %s: LME skipped (%s)\n', feat, ME.message);
        end
    end
else
    fprintf('fitlme not available; skipping LME models.\n');
end

if ~isempty(model_summaries)
    model_summaries = sortrows(model_summaries, 'p', 'ascend');
    writetable(model_summaries, fullfile(outpath,'LME_model_summary_all_features.csv'));
end

fprintf('\n=== EEG/RL analysis complete ===\n');
fprintf('RL-enriched feature table → %s\n', rl_feature_file);
fprintf('Figures and CSV outputs   → %s\n', outpath);

% =========================================================================
%% LOCAL FUNCTIONS
% =========================================================================

function T = standardise_key_columns_lc(T)
% Standardise common key-column variants to subjID, block, trial.
if ismember('subj_id', T.Properties.VariableNames) && ~ismember('subjID', T.Properties.VariableNames)
    T.subjID = T.subj_id;
end
if ismember('subject', T.Properties.VariableNames) && ~ismember('subjID', T.Properties.VariableNames)
    T.subjID = T.subject;
end
if ismember('blocknum', T.Properties.VariableNames) && ~ismember('block', T.Properties.VariableNames)
    T.block = T.blocknum;
end
if ismember('trialnum', T.Properties.VariableNames) && ~ismember('trial', T.Properties.VariableNames)
    T.trial = T.trialnum;
end
if ismember('subjID', T.Properties.VariableNames)
    T.subjID = string(T.subjID);
end
if ismember('block', T.Properties.VariableNames)
    T.block = double(T.block);
end
if ismember('trial', T.Properties.VariableNames)
    T.trial = double(T.trial);
end
if ismember('block_type', T.Properties.VariableNames)
    T.block_type = string(T.block_type);
    T.block_type(T.block_type == "V") = "P";
end
end

function T = add_nassar_to_group_table_lc(T, results)
cols = {'PE_nassar','omega','alpha_nassar','certainty','surprise','theta_nassar'};
for c = cols
    T.(c{1}) = nan(height(T), 1);
end
subjs = unique(string(T.subjID));
for si = 1:numel(subjs)
    sn = char(subjs(si));
    if ~isfield(results, sn), continue; end
    r = results.(sn);
    sm = string(T.subjID) == string(sn);
    sub_rows = find(sm);
    blocks_gt = double(T.block(sub_rows));
    trials_gt = double(T.trial(sub_rows));
    for ti = 1:numel(r.trial_id)
        match = sub_rows(blocks_gt == double(r.block_id(ti)) & trials_gt == double(r.trial_id(ti)));
        if isempty(match), continue; end
        T.PE_nassar(match)    = r.delta_trial(ti);
        T.omega(match)        = r.omega_trial(ti);
        T.alpha_nassar(match) = r.alpha_trial(ti);
        T.certainty(match)    = r.certainty_trial(ti);
        T.surprise(match)     = r.surprise(ti);
        T.theta_nassar(match) = r.theta_trial(ti);
    end
end
end

function T = add_behavioural_derived_columns_lc(T)
if ~ismember('rel_trial', T.Properties.VariableNames)
    if ismember('revTrial', T.Properties.VariableNames)
        T.rel_trial = double(T.trial) - double(T.revTrial);
    else
        T.rel_trial = nan(height(T),1);
    end
end
if ~ismember('stim_status', T.Properties.VariableNames)
    T.stim_status = repmat("unknown", height(T), 1);
    stim_col = '';
    if ismember('stimID', T.Properties.VariableNames), stim_col = 'stimID'; end
    if isempty(stim_col) && ismember('stimType', T.Properties.VariableNames), stim_col = 'stimType'; end
    if ~isempty(stim_col) && ismember('switch_stims', T.Properties.VariableNames)
        for ri = 1:height(T)
            sw = read_switch_value_lc(T.switch_stims, ri);
            if isempty(sw), sw = [2 3]; end
            sid = double(T.(stim_col)(ri));
            if isfinite(sid)
                if ismember(sid, sw)
                    T.stim_status(ri) = "switched";
                elseif ismember(sid, setdiff(1:4, sw))
                    T.stim_status(ri) = "maintained";
                end
            end
        end
    end
end
end

function sw = read_switch_value_lc(col, ri)
sw = [];
try
    if iscell(col), val = col{ri}; else, val = col(ri); end
    if isempty(val), return; end
    if isnumeric(val)
        sw = double(val(:)'); sw = sw(isfinite(sw));
    elseif isstring(val) || ischar(val)
        nums = regexp(char(val), '\d+', 'match');
        if ~isempty(nums), sw = cellfun(@str2double, nums); end
    end
catch
    sw = [];
end
end

function eeg_cols = find_eeg_feature_columns_lc(T, exclude_cols)
vars = T.Properties.VariableNames;
eeg_cols = {};
name_pat = '(frn|rewp|p300|p3|p2|n2|theta|alpha|beta|gamma|delta|erp|amp|amplitude|latency|power|plv|itpc|ersp|tf_|eeg|channel|cluster|front|pariet|central|sensor)';
for vi = 1:numel(vars)
    v = vars{vi};
    if any(strcmpi(v, exclude_cols)), continue; end
    x = T.(v);
    if ~isnumeric(x) || ~isvector(x), continue; end
    if mean(isfinite(x)) < 0.05, continue; end
    if ~isempty(regexpi(v, name_pat))
        eeg_cols{end+1} = v; %#ok<AGROW>
    end
end
if isempty(eeg_cols)
    % Fallback: numeric columns excluding obvious behavioural/model columns.
    for vi = 1:numel(vars)
        v = vars{vi};
        if any(strcmpi(v, exclude_cols)), continue; end
        x = T.(v);
        if isnumeric(x) && isvector(x) && mean(isfinite(x)) >= 0.05
            eeg_cols{end+1} = v; %#ok<AGROW>
        end
    end
end
end

function out = prioritize_eeg_features_lc(eeg_cols)
priority_pat = {'frn','rewp','p300','p3','theta','plv','itpc','power','amp','latency'};
score = zeros(numel(eeg_cols),1);
for ii = 1:numel(eeg_cols)
    nm = lower(eeg_cols{ii});
    for pi = 1:numel(priority_pat)
        if contains(nm, priority_pat{pi})
            score(ii) = score(ii) + (numel(priority_pat)-pi+1);
        end
    end
end
[~,idx] = sort(score,'descend');
out = eeg_cols(idx);
end

function plot_binned_lc(ax, x, y, nbins)
ok = isfinite(x) & isfinite(y);
x = x(ok); y = y(ok);
if numel(x) < nbins*5
    text(ax,0.5,0.5,'Insufficient data','Units','normalized','HorizontalAlignment','center');
    return;
end
edges = quantile(x, linspace(0,1,nbins+1));
edges = unique(edges);
if numel(edges) < 3
    text(ax,0.5,0.5,'No latent spread','Units','normalized','HorizontalAlignment','center');
    return;
end
nb = numel(edges)-1;
y_m = nan(nb,1); y_se = nan(nb,1); x_m = 1:nb;
for bi = 1:nb
    if bi == nb
        m = x >= edges(bi) & x <= edges(bi+1);
    else
        m = x >= edges(bi) & x < edges(bi+1);
    end
    vals = y(m);
    y_m(bi) = mean(vals,'omitnan');
    y_se(bi) = sem_lc(vals);
end
errorbar(ax, x_m, y_m, y_se, 'o-', 'LineWidth',1.5, 'MarkerFaceColor',[0.3 0.3 0.3]);
set(ax,'XTick',1:nb);
ylabel(ax,'EEG feature');
end

function [stim_status, epoch] = get_stim_and_epoch_lc(T)
if ismember('stim_status', T.Properties.VariableNames)
    stim_status = string(T.stim_status);
else
    stim_status = repmat("unknown", height(T), 1);
end
if ismember('rel_trial', T.Properties.VariableNames)
    rel = double(T.rel_trial);
    epoch = repmat("unknown", height(T), 1);
    epoch(rel < 0) = "pre";
    epoch(rel >= 0) = "post";
else
    epoch = repmat("unknown", height(T), 1);
end
end

function s = sem_lc(x)
x = x(isfinite(x));
if numel(x) < 2, s = NaN; else, s = std(x,'omitnan')/sqrt(numel(x)); end
end

function cmap = bluewhitered_lc(n)
if nargin < 1, n = 256; end
n1 = floor(n/2); n2 = n - n1;
blue = [0.1 0.25 0.8]; white = [1 1 1]; red = [0.8 0.1 0.1];
c1 = [linspace(blue(1),white(1),n1)', linspace(blue(2),white(2),n1)', linspace(blue(3),white(3),n1)'];
c2 = [linspace(white(1),red(1),n2)', linspace(white(2),red(2),n2)', linspace(white(3),red(3),n2)'];
cmap = [c1; c2];
end
